name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    name: Build, Test & Lint (Nx + npm)
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configura Node.js + cache do npm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Instala dependências usando npm
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Cache do Nx
      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: |
            .nx/cache
            node_modules/.cache
          key: nx-${{ runner.os }}-${{ hashFiles('**/project.json', '**/package.json', 'package-lock.json') }}
          restore-keys: |
            nx-${{ runner.os }}-

      # Lint
      - name: Lint
        run: npx nx run-many --target=lint --all

      # Testes
      - name: Test
        run: npx nx run-many --target=test --all --parallel --max-parallel=3

      # Build
      - name: Build
        run: npx nx run-many --target=build --all --parallel --max-parallel=3
